[tool.poetry]
name = "cyecca"
version = "0.1.0"
description = ""
authors = ["James Goppert <james.goppert@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pip = "^23.0"
install = "^1.3.5"
casadi = "3.5.6.pre2"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
pytest = "^7.2.1"
pre-commit = "^3.0.4"
flake8 = "^6.0.0"
mypy = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
