name: format
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Link with black
        run: /home/runner/.local/bin/poetry run black .
      - name: Test with pytest
        run: /home/runner/.local/bin/poetry run pytest

